esphome:
  name: $device_name
  platform: $platform
  board: $board

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 5min
  fast_connect: True
  power_save_mode: none
  output_power: 17.5dB
  # ap:
  #   ssid: $device_name
  #   password: !secret ap_password
  #   ap_timeout: 1min

# captive_portal:

api:

ota:
  password: !secret ota_password
  safe_mode: true

external_components:
  - source:
      type: local
      path: components

# Current time
sun:
  latitude: 49.9871°
  longitude: 21.9775°
  id: sun_home

time:
  - platform: homeassistant

sensor:
  - platform: wifi_signal
    name: $device_name WiFi Signal
    update_interval: 60s

switch:
  - platform: restart
    name: $device_name Restart
